name: hw4 ê¹ƒí—ˆë¸Œ ì•¡ì…˜ ì—°ìŠµí•˜ê¸°

# PRì´ ë§Œë“¤ì–´ì¡Œê±°ë‚˜ master ë¸Œëœì¹˜ì— ë¨¸ì§€ë˜ì–´ ì˜¬ë¼ê°ˆ ë•Œ ìˆ˜í–‰í•©ë‹ˆë‹¤.
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"
jobs:
  Hw4-GitHub-Action:
    runs-on: ubuntu-laatest
    name: hw4 ê¹ƒí—ˆë¸Œ ì•¡ì…˜ ì—°ìŠµí•˜ê¸° ğŸš€

    steps:
      - name: í˜„ì¬ ë””ë ‰í† ë¦¬ ì²´í¬ âœ…
        run: ls -al
      - name: checkout
        uses: actions/checkout@v3
      - name: í˜„ì¬ ë””ë ‰í† ë¦¬ ë‹¤ì‹œ ì²´í¬ âœ…
        run: ls -al
        run: cat .github/workflows/action.yml
      - name: í´ë”ì— ë‹¤ìš´ë¡œë“œ ë°›ê¸° âœ¨
        uses: actions/checkout@v3
        with:
          path: our-source
        run: ls -al
        run: ls -al our-source
