name: hw4 ê¹ƒí—ˆë¸Œ ì•¡ì…˜ ì—°ìŠµí•˜ê¸°

# PRì´ ë§Œë“¤ì–´ì¡Œê±°ë‚˜ master ë¸Œëœì¹˜ì— ë¨¸ì§€ë˜ì–´ ì˜¬ë¼ê°ˆ ë•Œ ìˆ˜í–‰í•©ë‹ˆë‹¤.
on:
  push:
    branches: [master]
  pull_request:
    branches:
      - "**"
jobs:
  GitHub-Action-Demo:
    runs-on: ubuntu-latest
    name: hw4 ê¹ƒí—ˆë¸Œ ì•¡ì…˜ ë°ëª¨

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: check directory
        run: ls -al
      - name: Run multi-line script
        run: |
          echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
          echo "ğŸ” The name of branch is ${{ github.ref }} and repository is ${{ github.repository }}."
